# Generated by Django 4.2.3 on 2023-08-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flavour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('variety', models.CharField(max_length=50)),
                ('total', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
